# Generated by Django 4.0.3 on 2022-04-07 00:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fitness.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3), fitness.common.validators.validate_only_letters_numbers_space])),
                ('youtube_link', models.URLField()),
                ('category', models.CharField(choices=[('ABS', 'ABS'), ('Arms', 'Arms'), ('Back', 'Back'), ('Chest', 'Chest'), ('Legs', 'Legs'), ('Shoulders', 'Shoulders')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3)])),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('category', models.CharField(choices=[('ABS', 'ABS'), ('Arms', 'Arms'), ('Back', 'Back'), ('Chest', 'Chest'), ('Legs', 'Legs'), ('Shoulders', 'Shoulders')], max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('weight', models.IntegerField(validators=[fitness.common.validators.validate_number_cannot_be_below_zero])),
                ('series', models.IntegerField(validators=[fitness.common.validators.validate_number_cannot_be_below_zero])),
                ('reps', models.IntegerField(validators=[fitness.common.validators.validate_number_cannot_be_below_zero])),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.workout')),
            ],
        ),
    ]
